# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'itunesstoretest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for itunesstoretest
  pod 'Alamofire'
  pod 'AlamofireNetworkActivityLogger', '~> 2.0'
  pod 'SDWebImage', '~> 5.0' 
  pod 'IQKeyboardManager'
  pod 'ReachabilitySwift'

end
